#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = waybar & swaync & hypridle
exec-once = matuwall --daemon 
exec-once = awww-daemon 
exec-once = swayosd-server
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = hyprpm reload
exec-once = systemctl --user start hyprpolkitagent
exec-once = snappy-switcher --daemon
