#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/

# https://wiki.hypr.land/Configuring/Variables/#general

source = ~/dotfiles/hyprland/.config/hypr/modules/colors.conf

general {
    gaps_in = 9
    gaps_out = 5

    border_size = 2

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = $primary
    col.inactive_border = $secondary

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = scrolling
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 0
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.95
    shadow {
        enabled = true
        range = 7
        render_power = 3
        color = $shadow
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 9
        passes = 2
        new_optimizations = true
        vibrancy = 0.1696
    }
}
# Layer Rules

layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center

layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window

# Window Rules

windowrule = match:title "Extension: (Bitwarden Password Manager) - Bitwarden — Zen Browser", float on
windowrule = match:class org.vinegarhq.Sober, fullscreen on
windowrule = match:class org.gnome.Calculator, float 1
windowrule = match:initial_class vlc, rounding 6
# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    force_split = 2
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}


